import { Foto } from "../types";

export const FOTOS_MOCK: Foto[] = [
  {
    id: 1,
    src: "/polaroids/polaroid1.webp",
    srcHighRes: "/polaroidsHiRes/Polaroid014.jpg",
    titulo: "Belén y yo en mi fiesta de cumpleaños ✨",
    fecha: "18/10/2025",
    ubicacion: "Casa de Joel, Iztapalapa, CDMX",
    categoria: "polaroids",
    top: "100px",
    left: "5%",
    rotate: "-rotate-3",
  },
  {
    id: 2,
    src: "/polaroids/polaroid0.webp",
    srcHighRes: "/polaroidsHiRes/Polaroid00.jpeg",
    titulo: "Elenco de Shrek en mi cumple",
    fecha: "2025",
    ubicacion: "Casa de Joel, Iztapalapa, CDMX",
    categoria: "polaroids",
    top: "750px",
    left: "4%",
    rotate: "rotate-6",
  },
  {
    id: 3,
    src: "/polaroids/polaroid2.webp",
    srcHighRes: "/polaroidsHiRes/Polaroid016.jpg",
    titulo: "Vista de mi cuarto",
    fecha: "18/10/2025",
    ubicacion: "Benito Juárez, CDMX",
    categoria: "polaroids",
    top: "300px",
    left: "60%",
    rotate: "-rotate-6",
  },
  {
    id: 4,
    src: "/polaroids/polaroid3.webp",
    srcHighRes: "/polaroidsHiRes/Polaroid018.jpg",
    titulo: "Salida de metro Ermita L12",
    fecha: "1/03/2026",
    ubicacion: "Benito Juárez, CDMX",
    categoria: "polaroids",
    top: "950px",
    left: "50%",
    rotate: "-rotate-2",
  },
  {
    id: 5,
    src: "/polaroids/polaroid4.webp",
    srcHighRes: "/polaroidsHiRes/Polaroid015.jpg",
    titulo: "Vista del CENART",
    fecha: "4/03/2026",
    ubicacion: "Benito Juárez, CDMX",
    categoria: "boneka",
    top: "1400px",
    left: "5%",
    rotate: "-rotate-5",
  },
  {
    id: 6,
    src: "/polaroids/polaroid5.webp",
    srcHighRes: "/polaroidsHiRes/Polaroid021.jpg",
    titulo: "Interior de la Casa del tiempo UAM",
    fecha: "18/10/2025",
    ubicacion: "Miguel Hidalgo, CDMX",
    categoria: "boneka",
    top: "2000px",
    left: "5%",
    rotate: "-rotate-5",
  },
  {
    id: 7,
    src: "/polaroids/polaroid6.webp",
    srcHighRes: "/polaroidsHiRes/Polaroid020.jpg",
    titulo: "Dogma y Nana",
    fecha: "1/11/2025",
    ubicacion: "Temascalcingo, Edo Mex",
    categoria: "boneka",
    top: "1600px",
    left: "60%",
    rotate: "rotate-5",
  },
  {
    id: 8,
    src: "/polaroids/polaroid8.webp",
    srcHighRes: "/polaroidsHiRes/Polaroid019.jpg",
    titulo: "Exterior de la Casa del tiempo UAM",
    fecha: "18/10/2025",
    ubicacion: "Miguel Hidalgo, CDMX",
    categoria: "boneka",
    top: "2200px",
    left: "55%",
    rotate: "-rotate-5",
  },
  {
    id: 9,
    src: "/polaroids/polaroid7.webp",
    srcHighRes: "/polaroidsHiRes/Polaroid017.jpg",
    titulo: "Retrato de Dogma con mi papá",
    fecha: "1/11/2025",
    ubicacion: "Temascalcingo, Edo Mex",
    categoria: "boneka",
    top: "2600px",
    left: "15%",
    rotate: "rotate-5",
  },
  {
    id: 10,
    src: "/polaroids/polaroid9.webp",
    srcHighRes: "/polaroidsHiRes/Polaroid010.jpg",
    titulo: "Vane, Joel y yo en mi fiesta de cumpleaños✨",
    fecha: "18/10/2025",
    ubicacion: "Casa de Joel, Iztapalapa, CDMX",
    categoria: "boneka",
    top: "2800px",
    left: "65%",
    rotate: "-rotate-4",
  },
  {
    id: 11,
    src: "/polaroids/polaroid10.webp",
    srcHighRes: "/polaroidsHiRes/Polaroid008.jpg",
    titulo: "Mis papás: Sonia y Aarón",
    fecha: "1/11/2025",
    ubicacion: "Temascalcingo, Edo Mex",
    categoria: "boneka",
    top: "3200px",
    left: "1%",
    rotate: "rotate-1",
  },
  {
    id: 12,
    src: "/polaroids/polaroid11.webp",
    srcHighRes: "/polaroidsHiRes/Polaroid013.jpg",
    titulo: "Gatito del vecino de abajo",
    fecha: "28/02/2026",
    ubicacion: "Benito Juarez, CDMX",
    categoria: "boneka",
    top: "3850px",
    left: "1%",
    rotate: "-rotate-6",
  },
  {
    id: 13,
    src: "/polaroids/polaroid13.webp",
    srcHighRes: "/polaroidsHiRes/Polaroid007.jpg",
    titulo: "Beléncita en su picnic de cumpleaños✨",
    fecha: "5/04/2026",
    ubicacion: "Parque Loreto y Peña Pobre, Tlalpan, CDMX",
    categoria: "boneka",
    top: "3500px",
    left: "60%",
    rotate: "rotate-3",
  },
  {
    id: 14,
    src: "/polaroids/polaroid15.webp",
    srcHighRes: "/polaroidsHiRes/Polaroid006.jpg",
    titulo: "Palacio de Bellas Artes",
    fecha: "1/03/2026",
    ubicacion: "Centro, CDMX",
    categoria: "boneka",
    top: "4100px",
    left: "50%",
    rotate: "rotate-2",
  },
  {
    id: 15,
    src: "/polaroids/polaroid12.webp",
    srcHighRes: "/polaroidsHiRes/Polaroid012.jpg",
    titulo: "Diego, Jacob, yo y Xime terminando la carrera nocturna 5K",
    fecha: "1/11/2025",
    ubicacion: "Temascalcingo, Edo Mex",
    categoria: "boneka",
    top: "4500px",
    left: "8%",
    rotate: "-rotate-4",
  },
  {
    id: 16,
    src: "/polaroids/polaroid14.webp",
    srcHighRes: "/polaroidsHiRes/Polaroid011.jpg",
    titulo: "Vista de la cineteca del CENART",
    fecha: "4/03/2026",
    ubicacion: "Benito Juárez, CDMX",
    categoria: "boneka",
    top: "4700px",
    left: "53%",
    rotate: "rotate-3",
  },
  {
    id: 17,
    src: "/polaroids/polaroid16.webp",
    srcHighRes: "/polaroidsHiRes/Polaroid005.jpg",
    titulo: "Bellas artes y la Torre Latino",
    fecha: "1/03/2026",
    ubicacion: "Centro, CDMX",
    categoria: "boneka",
    top: "5100px",
    left: "10%",
    rotate: "-rotate-3",
  },
  {
    id: 18,
    src: "/polaroids/polaroid17.webp",
    srcHighRes: "/polaroidsHiRes/Polaroid001.jpg",
    titulo: "Vista desde la escalera de los departamentos",
    fecha: "4/03/2026",
    ubicacion: "Benito Juárez, CDMX",
    categoria: "boneka",
    top: "5300px",
    left: "60%",
    rotate: "rotate-3",
  },
  {
    id: 19,
    src: "/polaroids/polaroid18.webp",
    srcHighRes: "/polaroidsHiRes/Polaroid002.jpg",
    titulo: "Vocho en calle Alfonso Caso",
    fecha: "4/03/2026",
    ubicacion: "Benito Juárez, CDMX",
    categoria: "boneka",
    top: "5700px",
    left: "10%",
    rotate: "-rotate-0",
  },
  {
    id: 20,
    src: "/polaroids/polaroid19.webp",
    srcHighRes: "/polaroidsHiRes/Polaroid003.jpg",
    titulo: "Vane, yo y Nurit en el tianguis de Portales",
    fecha: "07/03/2025",
    ubicacion: "Benito Juárez, CDMX",
    categoria: "boneka",
    top: "5900px",
    left: "60%",
    rotate: "-rotate-3",
  },

  {
    id: 21,
    src: "/polaroids/polaroid20.webp",
    srcHighRes: "/polaroidsHiRes/Polaroid004.jpg",
    titulo: "Flor frente a Ermita Iztapalapa",
    fecha: "04/03/2026",
    ubicacion: "Benito Juárez, CDMX",
    categoria: "boneka",
    top: "6300px",
    left: "15%",
    rotate: "-rotate-3",
  },
];
